workflows:
  ios-release:
    name: GCCI iOS Release
    instance_type: mac_mini_m2
    environment:
      flutter: 3.32.6
      xcode: 26.0
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build iOS IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
